

source 'https://github.com/CocoaPods/Specs.git'


target "JanusGateway" do
    pod 'CRToast', '~> 0.0.7'
    pod 'AFNetworking'
    pod 'SocketRocket'
    pod 'WebRTC', :git => 'https://github.com/Anakros/WebRTC.git'
end
